version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw test

  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build